/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../verilog/full_adder.v:1" *)
module full_adder(a, b, cin, S, Cout);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "../verilog/full_adder.v:1" *)
  output Cout;
  (* src = "../verilog/full_adder.v:1" *)
  output S;
  (* src = "../verilog/full_adder.v:1" *)
  input a;
  (* src = "../verilog/full_adder.v:1" *)
  input b;
  (* src = "../verilog/full_adder.v:1" *)
  input cin;
  \74AC32_4x1OR2  _4_ (
    .A(a),
    .B(cin),
    .Y(_1_)
  );
  \74AC00_4x1NAND2  _5_ (
    .A(a),
    .B(cin),
    .Y(_2_)
  );
  \74AC86_4x1XOR2  _6_ (
    .A(a),
    .B(cin),
    .Y(_3_)
  );
  \74AC86_4x1XOR2  _7_ (
    .A(b),
    .B(_3_),
    .Y(S)
  );
  \74AC00_4x1NAND2  _8_ (
    .A(b),
    .B(_1_),
    .Y(_0_)
  );
  \74AC00_4x1NAND2  _9_ (
    .A(_2_),
    .B(_0_),
    .Y(Cout)
  );
endmodule
