/* Generated by Yosys 0.34+9 (git sha1 a1923a5f7, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "/home/timdg/Documents/RTL/Verilog/full_adder.v:1.1-23.10" *)
module \$abstract\full_adder ();
endmodule
